// String is sequence of charchter . 

name = "Pratham";
college_Name = 'Gh Raisoni College of engeenering Nagpur';
city = "Gondia";
console.log( name , college_Name , city);

let alphabets = 'A';
console.log(alphabets);
console.log(typeof(alphabets));

let num = '9529754950'
console.log(typeof(num));
console.log(num);

let emp = " ";
console.log(typeof(emp));

let sentence = 'this is "my code"';
console.log(sentence);