// UNARY OPERATOR --> USE IN SINGLE OPERATOR 
// INCREMENT (++) AND DECREMENT (--)

// EXAMPLE OF INCREMENT OPERATOR 
// PRE-INCREMENT (USe then Assign)
let D_O_B = 2001;
x = ++D_O_B;
console.log(x);

//EXAMPLE OF POST INCREMENT OPERATOR
//POST-INCREMENT ( ASSIGN THEN USE) 
let Data_of_birth = 2001;
y = Data_of_birth++;
console.log(y);
console.log(Data_of_birth);

// EXAMPLE OF DCREMENT OPERATOR 
// PRE-DECREMENT (USe then Assign)
let DateOfBirth = 2001;
a = --DateOfBirth;
console.log(a);

// POST-DECREMENT (Assign then use)
let DateOfbirth = 2001;
m = DateOfbirth--;
console.log(m);
console.log(DateOfbirth);